global:
  scrape_interval: 1s
  evaluation_interval: 1s

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['localhost:9093']


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: obs
    scrape_interval: 1s
    static_configs:
      - targets: ['obsmon:8000']
